### ISSUE TITLE
issue if frozen_folder is not in root but in package.frozen_folder

### ISSUE THREAD

**Issue by temphstarmans** [bixb922/freezeFS#2]
Great package, i encountered a small issue.
If you place frozen_folder.py into package/frozen_folder.py I get a problem;

```python
module = __import__( module_name )
 if module_name != "__main__":
  del sys.modules[ module_name ]
 vp = _VerbosePrint( module_name, "extract", silent )
 vp.print( f"extracting files to {target}." )
 _extract_all( module.direntries, target, overwrite, vp )
``` 
Module.direntries fails as frozen_folder.direntries does not exisits it should be package.frozen_folder.direntries

**Comment by bixb922** [comment]
If you don't mind I would like you to test the latest version in this repository, or update using pip install --upgrade freezers to version 2.4.  There is a fix now for the situation you describe. ~I haven't updated pypi yet.~ I hope this solves your issue. 

Please let me know if it worked.

**Comment by temphstarmans** [comment]
It is fixed!! thanks
