### ISSUE TITLE
Micropython cannot find the module frozen with freezefs

### ISSUE THREAD

**Issue by RichardB-RT** [bixb922/freezeFS#3]
Hi, i am looking for a way to have a folder containing a website frozen into the micropython image and can be used to host a small website.
Using freezefs i would like to freeze a www folder containg 2 png pictures and a html file. The file structure is:
www
->Pic1.png
->Pic2.png
->index.html

Using the following command to put the folder in frozen_www.py: 
```python -m freezefs www frozen_www.py``` which indicates frozen_www.py written succesfully.

In the frozen_manifest.py i have the following:
```
module("boot.py")
module("main.py")
```
All files (boot.py, main.py, frozen_www.py and frozen_manifest.py) are placed in a folder /source

In boot.py is statement: "import frozen_www".
The command to build the firmware:
```
make BOARD=NUCLEO_L476RG FROZEN_MANIFEST=~/source/frozen_manifest.py
```
After flashing the micropython image to the board and pressing reset, the following error is shown in the REPL:
```
MPY: sync filesystems
MPY: soft reboot
Traceback (most recent call last):
  File "boot.py", line 2, in <module>
ImportError: no module named 'frozen_www'
```

What am i doing wrong here?

**Comment by bixb922** [comment]
I think that you need to include ```module("frozen_www.py")``` in the ```frozen_manifest.py``` manifest file. With that line in place, ```frozen_www.py``` is also included in the MicroPython image and can then be imported in ```boot.py```

You should be able to see the virtual ```www``` folder with your png and html files using ```mpremote ls```

Please tell if that worked.

**Comment by RichardB-RT** [comment]
Adding the frozen_www.py to the frozen_manifest.py did indeed work. By executing the commands 
`import os`
`os.listdir("/www")`
the files are listed.

Thank you!

**Comment by RichardB-RT** [comment]
Solved...
